### ISSUE TITLE
getNode fails when multiple segments of the path do not exist

### ISSUE THREAD

**Issue by icidasset** [wnfs-wg/rs-wnfs#222]
Calling `getNode([ "top-dir", "nested-dir", "file" ])` will result in an error instead of returning `null`. Where "top-dir" exists, but "nested-dir" and "file" do not.

Given error:
```
Error: Cannot get node: Invalid WNFS path
```

**Comment by appcypher** [comment]
How do you suggest we go about it? 
You could use a workaround by handling the error or we can introduce a variant of getNode that returns null with invalid paths.

**Comment by matheus23** [comment]
Since `getNode` already returns a `Result<Option<...>>`, and that's `Ok(None)` if the last part of the path is missing, it should simply also return `Ok(None)` when any other path segment is missing.
