### ISSUE TITLE
Private FS Work: APIs

### ISSUE THREAD

**Issue by matheus23** [wnfs-wg/rs-wnfs#30]
Implement FS APIs:
* `read`
* `write`
* `mkdir`
* `ls`
* `get_history` (or similar)

Contrary to the public side, this will likely *not* need `base_history_on`, but work differently, since stuff isn't content-addressed anymore & we don't necessarily need to "upgrade" nodes on the path anymore.

**Comment by appcypher** [comment]
> Implement FS APIs:
> ...
> * `ls`
> ...

The `ls` is just for local operations?
