### ISSUE TITLE
Implement seeking & seeking + recovering reads

### ISSUE THREAD

**Issue by matheus23** [wnfs-wg/rs-wnfs#46]
> This is a great start, but we should add some variants to this, specifically a `lookup_node` that *seeks*.
I.e. does the normal lookup, but then it tries to advance the ratchet of what it looked up to the most recent version it can find. That might reveal a newer version of a directory that actually *does* (or doesn't) have the next path segment.
> 
> We want to do seeking lookups because one peer may only have access to `private/Apps/flatmate` and so when writing the file `private/Apps/flatmate/state.json` it will only write the `state.json` and `flatmate` nodes.
> Then, when a peer reads the `private/Apps` directory, that will still link to the old `flatmate` directory, not the new one. So that peer needs to `seek` to newer versions.
> 
> (Also, I need to write down the seeking algorithm in the spec, and it should be probably implemented in the rs-skip-ratchet repo)

_Originally posted by @matheus23 in https://github.com/wnfs-wg/rs-wnfs/pull/38#discussion_r950340586_

- [x] Seeking
  - [b2eb6c21827b80379d6b7e05e07c57eabd3d2c19](https://github.com/wnfs-wg/rs-wnfs/commit/b2eb6c21827b80379d6b7e05e07c57eabd3d2c19)
  - https://github.com/wnfs-wg/rs-wnfs/pull/52

The different kinds of reads are described in the spec here:
https://github.com/wnfs-wg/spec/blob/main/spec/private-wnfs.md#path-resolving

**Comment by matheus23** [comment]
Noting here that I've used unusual terms in the spec right now. We've previously called "recovering reads" "cooperative rooting" which is more precise I think. Just an FYI for anyone coming across this

**Comment by appcypher** [comment]
Moving `collaborative rooting` into its own issue.
