### ISSUE TITLE
Private FileSystem Collaborative Rooting

### ISSUE THREAD

**Issue by appcypher** [wnfs-wg/rs-wnfs#57]

**Comment by matheus23** [comment]
I noticed we actually already do collaborative rooting on writes "accidentally".

On seeking writes we're first looking up the newest version of all nodes along the path using `get_path_nodes` and then we write the n+1 versions in `fix_up_path_nodes`: https://github.com/wnfs-wg/rs-wnfs/blob/appcypher/header-in-content/crates/fs/private/directory.rs#L411

This ensures collaborative rooting.

We... can call this done for now?

There's a slight improvement we could do which is collaborative rooting on reads, but that's an optimization and not required for WNFS to function correctly/efficiently necessarily.
