### ISSUE TITLE
Some minors issues while following README

### ISSUE THREAD

**Issue by thaodt** [wnfs-wg/rs-wnfs#63]
Hi, I described issues what I met while playing around with `rs-wnfs`. I know we're WIP, so any issues could happen. 

# Summary

## Problem
1. typo error in `README.md` line 193 `script/`
2. running script `rs-wnfs.sh` got permission denied.
3. Running build `rs-wnfs build --all` get `wasm-opt` command not found. 
4. Running `example/graph` following README.md there, got some errors in console:
![Screenshot_20220926_192438](https://user-images.githubusercontent.com/5485589/192438963-1f7bdcd7-90cc-448f-a38b-3426e537187a.png)

![image](https://user-images.githubusercontent.com/5485589/192439123-a051164d-9993-424f-86b6-1fcaa9671759.png)

### Impact
2. 
```
sh scripts/rs-wnfs.sh setup

::: Make script executable :::

::: Drop a link to it in /usr/local/bin :::
ln: failed to create symbolic link '/usr/local/bin/rs-wnfs': Permission denied

::: Failed to install :::
```
3. `/usr/local/bin/rs-wnfs: line 124: wasm-opt: command not found`

## Solution

1. need to correct typo, it should be `scripts/` instead of `script/`
2. Upon checking, the script line 237 we made a symlink to `/usr/local/bin/` area which is required root privilege. Therefore I recommend using `sudo` and update README correspondingly.
3. Im on Manjaro Linux, need to install `binaryen` by `sudo pacman -Sy binaryen`.
4. Upon checking, the 404 requests are fetched under SSL (https). And it seems they were requested 2 times (1 is http and the other is ssl enabled). Im not sure there is a way to disable it on local machine or I'm missing something.

**More information**

**Desktop:**

- OS kernel: 5.15.65-1-MANJARO 
- Browser [e.g. chrome, safari]: Chrome Version 104.0.5112.101 (Official Build) (64-bit) (same thing happened with my Firefox).

I'm pleased to help further to the project (by creating any PRs) if its fine.

**Comment by matheus23** [comment]
Thanks for the second set of eyes! :eyes: 

Can you try opening the page with `localhost:8080` instead of `127.0.0.1:8080`?

**Comment by matheus23** [comment]
> I'm pleased to help further to the project (by creating any PRs) if its fine.

You're welcome to! :)

**Comment by thaodt** [comment]
> Thanks for the second set of eyes! eyes
> 
> Can you try opening the page with `localhost:8080` instead of `127.0.0.1:8080`?

yay, already tried, still the same issue.

**Comment by matheus23** [comment]
Hm. Yeah. I'm not sure what's happening here. Apparently `jsdelivr` responds with `content-type: text/plain` for `.js` files (cached from cloudflare) & `x-content-type-options: nosniff`, which causes the browser to reject the files as javascript.

I'm unsure how it used to work. Tagging @appcypher for help :eyes:

**Comment by matheus23** [comment]
It's weird. This example is also uploaded to https://calm-thin-barista.fission.app/ and there the `jsdelivr` works just fine.

**Comment by thaodt** [comment]
> It's weird. This example is also uploaded to https://calm-thin-barista.fission.app/ and there the `jsdelivr` works just fine.

Hmmm, lemme check further details at night 😄 thank for ur information

**Comment by matheus23** [comment]
@zeeshanlakhani concurrently has fixed one of these issues in #64 😅

**Comment by zeeshanlakhani** [comment]
@matheus23 ah sorry. I should have seen this.

**Comment by zeeshanlakhani** [comment]
on OSX (Monterey)/Chrome, no perms or wasm-opt issues. However, I also ran into similar js-deliver issues it seems:

<img width="745" alt="Screen Shot 2022-09-27 at 4 22 56 PM" src="https://user-images.githubusercontent.com/202820/192627948-0ced464e-6065-476f-ba74-491f4356c831.png">

<img width="1454" alt="Screen Shot 2022-09-27 at 4 22 41 PM" src="https://user-images.githubusercontent.com/202820/192627916-d05b1fac-c4fc-490c-ba0b-5bb8fbf81c83.png">

**Comment by thaodt** [comment]
> It's weird. This example is also uploaded to https://calm-thin-barista.fission.app/ and there the `jsdelivr` works just fine.

Can you tell more about the deployment process on this? Maybe its different from local machine or we missed something.

**Comment by appcypher** [comment]
Thanks for taking a look at this @thaodt and @zeeshanlakhani.
 
The 404 errors are from a webpack issue and can be ignored for now. But the main issue is that the example hasn't been updated in a while.

I will fix that in a new PR.
