### ISSUE TITLE
Standards for contribution + library documentation/clean-up

### ISSUE THREAD

**Issue by zeeshanlakhani** [wnfs-wg/rs-wnfs#71]
# Summary

Let's better our series of contribution information and how to get started in developing for rs-wnfs. I'm always heavily influenced

- [ ] Double-check visibility on fns/structs/etc, and make sure all pub fns are documented. 
- [x] leverage [pre-commit][https://pre-commit.com/] for forcing standard formatting, etc
- [x] Contribution Guideline (probably across Fission [Rust] projects). We have a lot of the templates already, but we should have a good overall, guide. 
- [x] Runnable examples and doc tests. WIP: https://github.com/wnfs-wg/rs-wnfs/pull/68
- [x] Tag workflow and crate release flow for rs-wnfs/skip-ratchet & rs-ucan.

**Comment by matheus23** [comment]
Now that we have https://github.com/fission-codes/rust-template/blob/main/CONTRIBUTING.md, can we close this?

(& should we do another run through pub fns/structs/etc?)

**Comment by matheus23** [comment]
First item in here will kinda always be in flux. We're still constantly looking at what to expose / what to hide & fixing up documentation constantly.

We did a bunch of passes recently with #198 and #184. I'll close this now.
